language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t dzuongld/docker-multi -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dzuongld/docker-multi npm run test

after_success:
    - docker build -t dzuongld/docker-multi-client ./client
    - docker build -t dzuongld/docker-multi-nginx ./nginx
    - docker build -t dzuongld/docker-multi-server ./server
    - docker build -t dzuongld/docker-multi-worker ./worker

    # Login
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Push to Docker Hub
    - docker push dzuongld/docker-multi-client
    - docker push dzuongld/docker-multi-nginx
    - docker push dzuongld/docker-multi-server
    - docker push dzuongld/docker-multi-worker
